# KingbaseES 连接配置 (Docker环境)
jdbc.driverClassName=com.kingbase8.Driver
# 重要：改为虚拟机的实际IP地址
jdbc.url=jdbc:kingbase8://192.168.100.22:54321/test?useUnicode=true&characterEncoding=utf8
jdbc.username=system
jdbc.password=Passw0rd
maxActive=50
maxIdle=20
maxWait=60000